title: Hello, world! I'm Billy Okeyo
description: I am a software engineer with a burning passion to want and help others with code that I create. I enjoy the limitless potential of impact that I can have with what I build, it is what pushes me every day to become a better developer.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.billyokeyo.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Billy Okeyo # add your name
author-img: billy-avatar.png # add your photo
about-author: I am a software engineer building products in Python(Django), Flutter, JavaScript and .NET. I enjoy the limitless potential of impact that I can have with what I build, it is what pushes me every day to become a better developer. Outside of coding, you can find me watching movies, playing video games and contributing to open source. I am a Well-organized person and a problem solver interested in the entire web development spectrum, cloud computing and recently started out on Cloud DevOps. # add description
social-twitter: Billy_de_Cartel
social-facebook: # add your Facebook handle
social-github: cartel360 # add your Github handle
social-linkedin: billy-okeyo # add your Linkedin handle
social-email: # add your Email address

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics:  Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
